### ISSUE TITLE
"overlay" app notifications

### ISSUE THREAD

**Issue by crivchri** [iboalali/sysnotifsnooze#1]
Please also make it work for "overlay" app notifications.
Text in french is: "s'affiche sur autres applis"
Thx a lot!

**Comment by percula** [comment]
I have addressed this issue for English and French in #2. Hopefully @iboalali will merge and update the app soon! If not let me know and I'll send you an apk ;-)

**Comment by iboalali** [comment]
The overlay app notification (displaying over other apps) can be disabled from the system. No need for an app.
That is the only reason I didn't include it in my app.
Thank you for your effort

**Comment by iboalali** [comment]
![screenshot_20170907-033353](https://user-images.githubusercontent.com/5447995/30191969-b8ba4a76-9444-11e7-93b1-4e276de9ae16.png)

here a screenshot of the displaying over other apps notification disabled

**Comment by percula** [comment]
Ah cool. Thanks!

**Comment by crivchri** [comment]
@iboalali How to you display this screen?

**Comment by iboalali** [comment]
@crivchri what screen, do you mean?

**Comment by japhir** [comment]
@iboalali I think they mean where to find the menu you showed a picture of, I'm also having trouble. Went through pretty much everything in notifications and in developer settings...

EDIT: This website explains how to do it for people like me who couldn't find it 😅 https://www.howtogeek.com/325193/how-to-disable-the-is-displaying-over-other-apps-notification-on-android-oreo/

**Comment by japhir** [comment]
This website explains how to do it for people like me who couldn't find it 😅
