### ISSUE TITLE
Include the Notification string in "permission_request_msg"

### ISSUE THREAD

**Issue by iboalali** [iboalali/sysnotifsnooze#27]
@Rakau please change the wording of these translations to include the Notification string "running in the background" and "using battery" but as %s like in English. so I can you the appropriate notification string at runtime of the app

https://github.com/iboalali/sysnotifsnooze/blob/184f5d1c7ed46e2a8bcc6da078b17006d7123fc9/app/src/main/res/values-zh-rCN/strings.xml#L17
https://github.com/iboalali/sysnotifsnooze/blob/184f5d1c7ed46e2a8bcc6da078b17006d7123fc9/app/src/main/res/values-zh-rHK/strings.xml#L17
https://github.com/iboalali/sysnotifsnooze/blob/184f5d1c7ed46e2a8bcc6da078b17006d7123fc9/app/src/main/res/values-zh-rTW/strings.xml#L17

If there are any questions, don't hesitate and ask me.
Thank you for you time

**Comment by Rakau** [comment]
Ok, I will take time to edit it, because the problem of jet lag may be a
little late

2017年11月21日 02:56，"Ibrahim Al-Alali" <notifications@github.com>写道：

**Comment by iboalali** [comment]
@Rakau 
You did exactly the opposite of what I asked for in your pull request 😆 

change the above three strings to include the notification string in the message either this one
https://github.com/iboalali/sysnotifsnooze/blob/a2b371edffc9ed279b018b52ce564aa3ab3c387b/app/src/main/res/values-zh-rCN/strings.xml#L9
or this one
https://github.com/iboalali/sysnotifsnooze/blob/a2b371edffc9ed279b018b52ce564aa3ab3c387b/app/src/main/res/values-zh-rCN/strings.xml#L12
so I can replace it with **%s**
