### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by jomo** [iboalali/sysnotifsnooze#3]
This looks like a very useful app!
Can you consider making it available through [F-Droid](https://f-droid.org/docs/FAQ_-_App_Developers/) as well, so users without Google Play Store can use it as well?

**Comment by iboalali** [comment]
Thank you for telling me, hadn't considered it.
I will look into it, but no promises.

**Comment by shawngustaw** [comment]
Hi @iboalali,

Hope you don't mind but I went ahead and forked this repo and have prepared it for an upload to F-Droid. Usually people who use FDroid don't have access to Google Play Services and/or don't trust running them on their device so I removed the in-app billing stuff. I've done my best to attribute all the work back to you and if I make any updates to the app I'll make sure to push them back up to you so you can include them in the Playstore version. 

Thanks again for putting this together. It's kind of odd that you had to but I'm grateful regardless :P 

Regards,
Shawn

**Comment by iboalali** [comment]
Hi @shawngustaw,
I don't mind, I just didn't have the time for it, because my day job is consuming my live currently.
Thank you for your effort.

Sincerely
ibo

**Comment by pushcx** [comment]
@shawngustaw Have you had any luck submitting to F-Droid? There's a Signal/Noise issue that mentions sysnotifsnooze as the only viable workaround: https://github.com/WhisperSystems/Signal-Android/issues/7255

**Comment by TPS** [comment]
@iboalali: @gloomy-ghost's #33 accomplishes @ least part of the precursor work for this.  Would you consider it, @ least as a build flavor?  I could contribute the F-Droid RFP & work w/ some contacts there to continue the ball rolling toward getting this done.

**Comment by IzzySoft** [comment]
[Tagging releases](https://github.com/iboalali/sysnotifsnooze/releases) and attaching the APK there could already bring it into [my repo](https://apt.izzysoft.de/fdroid), which can easily be used with the F-Droid client. From there on I could probably help you getting it to F-Droid.org itself (disclosure: I'm one of the maintainers there).

**Comment by TPS** [comment]
@shawngustaw Perhaps your fork would be better to include in F-Droid, if you could keep it up-to-date.  Alternatively, if you could contribute your work to make this F-Droid-compatible _back_ here as a flavor, maybe @iboalali could merge (& do the updates mentioned previously) so that @IzzySoft has a good path forward.
