### ISSUE TITLE
Fails on new Pixel 2

### ISSUE THREAD

**Issue by aav7fl** [iboalali/sysnotifsnooze#5]
This no longer seems to work on my new Pixel 2. I'm running the September 5 2017 Android patches with Android 8.0.0. The seemed to work just fine on my Nexus 5x even with the October 5 2017 patches. 

I'm not really sure what Google changed with the pixel release of Android, but it looks like they might have made a specific implementation for it.

**Comment by aav7fl** [comment]
It may have started working overnight? Seems odd. It wasn't working after a reboot yesterday, but now it is? I'm going to follow this a bit more closely.  I'll re-open if this returns.

**Comment by aav7fl** [comment]
Issue returned back later this morning. I suppose this wasn't resolved overnight.

**Comment by aav7fl** [comment]
Interesting.  It looks like I can now disable this notification on my Pixel 2 on the system level and it works.

![screenshot_20171019-083508](https://user-images.githubusercontent.com/3487107/32103861-234e3740-baf0-11e7-8523-29678ede5e5f.png)

**Comment by iboalali** [comment]
I will look into it.
But like you said, it's interesting that it can be disabled on the Pixel but no where else.
