### ISSUE TITLE
on lineage_oneplus3-userdebug 8.0.0 don't work

### ISSUE THREAD

**Issue by cheetah747** [iboalali/sysnotifsnooze#8]
on lineage_oneplus3-userdebug 8.0.0 don't work..full version is :lineage_oneplus3-userdebug 8.0.0 OPR6.170623.021 6c17f47bcc test-keys.

I forget to get the screenshot.....but however,nothing changed after I installed it....the system notification always visible

**Comment by iboalali** [comment]
I'm need a screenshot of the notification to help

**Comment by cheetah747** [comment]
i‘m sure that screenshot  help nothing.   nothing is show.

**Comment by iboalali** [comment]
You said the system notification is always visible, so a screenshot of the notification would help, otherwise I can't help.
